using CsharpTheory;


#region Problem description
// This game is meant for two or more players. In the game, each player starts out with 50 points,
// as each player takes a turn rolling the dice; the amount generated by the dice is 
//subtracted from the player’s points.The first player with exactly one point remaining wins.
// If a player’s remaining points minus the amount generated by the dice results in a value
//less than one, then the amount should be added to the player’s points. 
//
//Write a program that simulates the game being played by two players.Use the Die class that was presented 
//in Chapter 6 to simulate the dice.Write a Player class to simulate the player.
//Enter the player’s names and display the die rolls and the totals after each round.
#endregion

namespace Chapter8_ClassesAndObjects
{
    class FirstToOneGame
    {
        public static void Run()
        {
            int gameTime = 10;
            Dice dice = new Dice(6);


            Player player1 = new Player("Nick", 25);
            Player player2 = new Player("Nata", 25);


            int player1Points, player2Points;

            for (int i = 1; i < gameTime; i++)
            {
                player1Points = player1.Points -= dice.Roll();
                player2Points = player2.Points -= dice.Roll();

                // within the range of 10 but 1 is preferred 
                if (player1Points == 1)
                {
                    System.Console.WriteLine($"{player1.Name} is a winner!!!");
                    break;

                }
                else if (player1Points < 1)
                {
                    player1.Points += dice.Roll();

                }
                else if (player2Points == 1)
                {
                    System.Console.WriteLine($"{player2.Name} is a winner!!!");
                    break;
                }
                else if (player2Points < 1)
                {
                    player2.Points += dice.Roll();

                }
            }
        }
    }

    class Player
    {

        public string Name { get; set; }
        public int Points { get; set; }

        public Player(string name, int points)
        {
            Name = name;
            Points = points;
        }
    }
}
